[package]
name = "codespaces-blank"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive"] }
excelize = "0.0.1"
polars = { version = "0.46.0", features = ["lazy"] }
regex = "1"
